### ISSUE TITLE
Parameterized Docker JVM Flags

### ISSUE THREAD

**Issue by ubhaller** [UbiqueInnovation/workflows-backend#9]
The docker JVM Flags are hard coded in the `mvn_docker_image` action.
```-Djib.container.jvmFlags=-XX:MinRAMPercentage=60.0,-XX:MaxRAMPercentage=80.0```
These should be paramterized, or better use the `JAVA_OPTS` value from the `deployment.yaml`

**Comment by ubamrein** [comment]
Fixed with https://github.com/UbiqueInnovation/workflows-backend/pull/43. We use `ADDITIONAL_JAVA_OPTS` to prevent unwanted sideeffects of possible old deployments setting the old used `JAVA_OPTS` environment var.
